### ISSUE TITLE
no module named configparser

### ISSUE THREAD

**Issue by HammyHavoc** [feelfreelinux/ChatPlug#19]
Hi!

I run `python main.py` and I'm presented with this:
```
Traceback (most recent call last):
  File "main.py", line 1, in <module>
    from facegram.facegrambridge import FacegramBridge
  File "/home/hammyhavoc/ChatPlug/facegram/facegrambridge.py", line 1, in <module>
    from .config import FacegramConfig
  File "/home/hammyhavoc/ChatPlug/facegram/config.py", line 1, in <module>
    import configparser
ImportError: No module named configparser
```

**Comment by HammyHavoc** [comment]
So after running `sudo pip install configparser` and `sudo pip install pathlib`, I get this:

`ImportError: No module named fbchat.models`

**Comment by HammyHavoc** [comment]
Now I've run `pip install fbchat`, and now when running `python main.py` I get this:

`ImportError: No module named pyrogram.api`

**Comment by HammyHavoc** [comment]
So I finally get the script running! Yay! :- )

Now I just have to deal with this:

`Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/fbchat/client.py", line 1542, in _parseMessage
    thread_id=thread_id, thread_type=thread_type, ts=ts, metadata=metadata, msg=m)
  File "/home/hammyhavoc/ChatPlug/facegram/fbclienthandler.py", line 9, in onMessage
    self.bridge.facebookMessageHandler(author_id, message_object, thread_id, thread_type)
  File "/home/hammyhavoc/ChatPlug/facegram/bridge.py", line 29, in facebookMessageHandler
    thread = self.networkClient.createConversation(thread_id)
  File "/home/hammyhavoc/ChatPlug/facegram/networkclient.py", line 49, in createConversation
    title=thread.name
  File "/home/hammyhavoc/.local/lib/python3.6/site-packages/pyrogram/client/client.py", line 865, in send
    r = self.session.send(data, retries, timeout)
  File "/home/hammyhavoc/.local/lib/python3.6/site-packages/pyrogram/session/session.py", line 413, in send
    return self._send(data, timeout=timeout)
  File "/home/hammyhavoc/.local/lib/python3.6/site-packages/pyrogram/session/session.py", line 400, in _send
    Error.raise_it(result, type(data))
  File "/home/hammyhavoc/.local/lib/python3.6/site-packages/pyrogram/api/errors/error.py", line 71, in raise_it
    )(x=x)
pyrogram.api.errors.exceptions.bad_request_400.UsersTooFew: [400 USERS_TOO_FEW]: Not enough users (to create a chat, for example)`

I get this when a message is received.

**Comment by HammyHavoc** [comment]
I try a manual import and get this error:

`Traceback (most recent call last):
  File "/home/hammyhavoc/.local/lib/python3.6/site-packages/pyrogram/client/dispatcher/dispatcher.py", line 174, in update_worker
    else None)
  File "/home/hammyhavoc/.local/lib/python3.6/site-packages/pyrogram/client/dispatcher/dispatcher.py", line 128, in dispatch
    handler.callback(*args)
  File "/home/hammyhavoc/ChatPlug/facegram/commands_handler.py", line 33, in handleImport
    client.send_message("Exception occured while importing data")
TypeError: send_message() missing 1 required positional argument: 'text'`

**Comment by HammyHavoc** [comment]
Finally figured it out; the username in the config.ini refers to the user that you want to receive the messages on, not the user with the API credentials; could do with being spaced out accordingly or reworded in the config.ini to be less confusing.
