### ISSUE TITLE
"Traceback (most recent call last):"

### ISSUE THREAD

**Issue by RingCell** [feelfreelinux/ChatPlug#6]
I'm not sure what's the problem as all the fields in confing.ini are ok. So I'll leave some of the output here (the remaining output it's related to my FB profile. groups, friends...).
xx = my e-mail
Output:

Logging in xx...
Login of xx successful.
Pyrogram v0.7.4, Copyright (C) 2017-2018 Dan Tès <https://github.com/delivrance>
Licensed under the terms of the GNU Lesser General Public License v3 or later (LGPLv3+)

Registered commands
Traceback (most recent call last):
  File "main.py", line 4, in <module>
    bridge.startBridge()
  File "/home/ubuntu/facegram/facegram/facegrambridge.py", line 16, in startBridge
    CommandsHandler(self.networkClient, self.bridge, self.config)
  File "/home/ubuntu/facegram/facegram/commands_handler.py", line 10, in __init__
    self.threads = self.networkClient.fbClient.fetchThreadList()
  File "/home/ubuntu/.local/lib/python3.6/site-packages/fbchat/client.py", line 808, in fetchThreadList
    return [graphql_to_thread(node) for node in j['viewer']['message_threads']['nodes']]
  File "/home/ubuntu/.local/lib/python3.6/site-packages/fbchat/client.py", line 808, in <listcomp>
    return [graphql_to_thread(node) for node in j['viewer']['message_threads']['nodes']]
  File "/home/ubuntu/.local/lib/python3.6/site-packages/fbchat/graphql.py", line 206, in graphql_to_thread
    raise FBchatException('Unknown thread type: {}, with data: {}'.format(thread.get('thread_type'), thread))
 ...

**Comment by feelfreelinux** [comment]
Looks like a problem with library I'm using (fbchat)[https://github.com/carpedm20/fbchat/issues]. Do you have anything other than normal facebook groups / friends in your recent facebook messages?

**Comment by RingCell** [comment]
@feelfreelinux I have one group and 2 private chats. The account that I use to create the Bridge on FB is the same that I use to bridge Discord and FB.  Obviously, I've deleted the project on my hosting service (FB-Discord) so that it didn't interfere with this bot.
I can give it a try by creating a fresh profile, although I don't think that could be the cause.
I will come back and after that and if the problem persists I will pass the full log.

Thank you.

**Comment by RingCell** [comment]
@feelfreelinux 
After I've made a new account and installed tgcrypto (as the log suggests me), I manage to make it "run" using these commands:
pip3 install --upgrade tgcrypto
pip install --upgrade pip

Also, the /help command works now.
However, as soon as somebody texts me in private or in a group, the following error shows up:

(in private)
`Registered commands
Listening...
Messages seen by 100011199331508 in 1844064765651550 (GROUP) at 1528992292.588s
Exception in parsing of {'ofd_ts': 1528992295423, 'queue': 100026764901820, 'delta': {'class': 'NewMessage', 'attachments': [], 'irisSeqId': '116', 'messageMetadata': {'skipSnippetUpdate': False, 'messageId': 'mid.$cAAAADOfIQQhqMFAxq1j_wtAVchBk', 'offlineThreadingId': '6413058593367658596', 'threadKey': {'otherUserFbId': '100011199331508'}, 'tags': ['source:chat:web'], 'actorFbId': '100011199331508', 'timestamp': '1528992295339'}, 'body': 'Hmmmm'}, 'type': 'delta', 'iseq': 116}
Traceback (most recent call last):
  File "/home/olime/.local/lib/python3.5/site-packages/fbchat/client.py", line 1521, in _parseMessage
    thread_id=thread_id, thread_type=thread_type, ts=ts, metadata=metadata, msg=m)
  File "/home/olime/facegram/facegram/fbclienthandler.py", line 9, in onMessage
    self.bridge.facebookMessageHandler(author_id, message_object, thread_id, thread_type)
  File "/home/olime/facegram/facegram/bridge.py", line 29, in facebookMessageHandler
    thread = self.networkClient.createConversation(thread_id)
  File "/home/olime/facegram/facegram/networkclient.py", line 49, in createConversation
    title=thread.name
  File "/home/olime/.local/lib/python3.5/site-packages/pyrogram/client/client.py", line 805, in send
    r = self.session.send(data)
  File "/home/olime/.local/lib/python3.5/site-packages/pyrogram/session/session.py", line 417, in send
    return self._send(data)
  File "/home/olime/.local/lib/python3.5/site-packages/pyrogram/session/session.py", line 404, in _send
    Error.raise_it(result, type(data))
  File "/home/olime/.local/lib/python3.5/site-packages/pyrogram/api/errors/error.py", line 71, in raise_it
    )(x=x)
pyrogram.api.errors.exceptions.bad_request_400.UsersTooFew: [400 USERS_TOO_FEW]: Not enough users (to create a chat, for example)
Inbox event: 1, 1, 1`

(and the one below it's from a group)

`Registered commands
Listening...
Inbox event: 1, 1, 1
Marked messages as seen in threads [('100011199331508', 'USER')] at 1528992628.995s
Marked messages as seen in threads [('1844064765651550', 'GROUP')] at 1528992633.766s
Inbox event: 0, 0, 0
Exception in parsing of {'queue': 100026764901820, 'ofd_ts': 1528992638846, 'iseq': 121, 'type': 'delta', 'delta': {'class': 'NewMessage', 'irisSeqId': '121', 'body': '¿Este?', 'messageMetadata': {'timestamp': '1528992638770', 'tags': ['source:chat:web'], 'offlineThreadingId': '6413060033959593412', 'messageId': 'mid.$gAAaNKslMql5qMFVvMlj_xB9_aoXE', 'threadKey': {'threadFbId': '1844064765651550'}, 'actorFbId': '100011199331508'}, 'attachments': [], 'ttl': 'TTL_OFF'}}
Traceback (most recent call last):
  File "/home/olime/.local/lib/python3.5/site-packages/fbchat/client.py", line 1521, in _parseMessage
    thread_id=thread_id, thread_type=thread_type, ts=ts, metadata=metadata, msg=m)
  File "/home/olime/facegram/facegram/fbclienthandler.py", line 9, in onMessage
    self.bridge.facebookMessageHandler(author_id, message_object, thread_id, thread_type)
  File "/home/olime/facegram/facegram/bridge.py", line 29, in facebookMessageHandler
    thread = self.networkClient.createConversation(thread_id)
  File "/home/olime/facegram/facegram/networkclient.py", line 49, in createConversation
    title=thread.name
  File "/home/olime/.local/lib/python3.5/site-packages/pyrogram/client/client.py", line 805, in send
    r = self.session.send(data)
  File "/home/olime/.local/lib/python3.5/site-packages/pyrogram/session/session.py", line 417, in send
    return self._send(data)
  File "/home/olime/.local/lib/python3.5/site-packages/pyrogram/session/session.py", line 404, in _send
    Error.raise_it(result, type(data))
  File "/home/olime/.local/lib/python3.5/site-packages/pyrogram/api/errors/error.py", line 71, in raise_it
    )(x=x)
pyrogram.api.errors.exceptions.bad_request_400.UsersTooFew: [400 USERS_TOO_FEW]: Not enough users (to create a chat, for example)
Inbox event: 1, 1, 1
Marked messages as seen in threads [('1844064765651550', 'GROUP')] at 1528992643.698s
Inbox event: 0, 0, 0`

I don't know why it says "not enough users"...
Also, when I use "/import 1" it says nothing. On the other hand I'm confused as I don't know if I should use "/import 1" or "/import #1".

**Comment by feelfreelinux** [comment]
@RingCell You need two separate telegram accounts to use this app:
- First account its your private telegram account that you use every day, configure its telegram username / handle in `config.ini`
- Second account needs to act as bridge, configure its `api_hash` and `api_id` in `config.ini`.

**Comment by feelfreelinux** [comment]
I should make it more clear in readme tho

**Comment by RingCell** [comment]
@feelfreelinux It worked!

I thought that those tree fields were completely related (username, api_hash_ and api_id). You should definitely put a comment on the first line specifying that it doesn't have to be the "bot" username.

So... Even if everything is working right now there is a behavior of the bot that I don't understand.
When I use "/import 1" (which is the FB group id) in my Telegram group, it creates a new group instead of linking the current one with the FB group.

Maybe that's the intended behavior or I'm missing something. Sorry, if this is no related to the main issue but I feel like it's better than create a new "issue" at the moment.

**Comment by Bjornskjald** [comment]
Closed as it's related to Python version.
